[mongodb]
localhost

[catalogue]
localhost

[redis]
localhost

[user]
user-dev.sanathananelaform.online

[cart]
cart-dev.sanathananelaform.online

[mysql]
mysql-dev.sanathananelaform.online

[shipping]
shipping-dev.sanathananelaform.online

[rabbitmq]
rabbitmq-dev.sanathananelaform.online

[payment]
payment-dev.sanathananelaform.online

[frontend]
frontend-dev.sanathananelaform.online
